---

- name: Проверка, есть ли docker image '{{ current_image }}' на удалённом хосте
  shell: |
    docker images --format '{{ format_tempate }}' --filter 'reference={{ current_image }}'
  vars:
    format_tempate: !unsafe '{{.Repository}}:{{.Tag}}'
  register: current_image_exists

# Выполняется, если Docker images отсутствует
- include_tasks: image-transfer.yml
  when: image_transfer_force|bool == true or current_image_exists.stdout|length == 0
