---

- name: Проверка, есть ли имидж '{{ current_image }}' на удалённом хосте
  shell: |
    docker images --format '{{ format_tempate }}' --filter 'reference={{ current_image }}'
  vars:
    format_tempate: !unsafe '{{.Repository}}:{{.Tag}}'
  register: current_image_exists

- name: Передача имиджа '{{ current_image }}'
  block:

    - name: Print
      debug:
        msg: EXIST

  when: current_image_exists.stdout | length > 0
